### ISSUE TITLE
I get an error `Could not find a declaration file for module

### ISSUE THREAD

**Issue by artemismars** [SavvyWombat/tailwindcss-grid-areas#2] opened 2022-02-23 16:09 UTC
```js
var require: NodeRequire
(id: string) => any
Could not find a declaration file for module '@savvywombat/tailwindcss-grid-areas'. 
'C:/Users/user/Desktop/node/study/responsive-grid/node_modules/@savvywombat/tailwindcss-grid-areas/src/plugin.js' 
implicitly has an 'any' type.
Try `npm i --save-dev @types/savvywombat__tailwindcss-grid-areas` 
if it exists or add a new declaration (.d.ts) file containing `declare module '@savvywombat/tailwindcss-grid-areas';`
ts(7016)
```

this error occurs from the code below

```js
// in tailwind.config.js
plugins: [require('@savvywombat/tailwindcss-grid-areas')]
```

**Comment by horuskol** [comment] 2022-02-24 06:02
Hi, I haven't done any work with TypeScript before, and the plugin is vanilla JavaScript. In the meantime, you can do as suggested in the above message:

> add a new declaration (.d.ts) file containing `declare module '@savvywombat/tailwindcss-grid-areas';`

**Comment by horuskol** [comment] 2022-04-26 22:52
Hi again,

I've tried to make a simple failing project to reproduce the problem and develop a fix, but I'm not getting the error. If you're still having trouble, would you be able to provide a simple failing project, or a link to a repo/branch?

**Comment by horuskol** [comment] 2022-08-31 23:52
I'm going to close this issue, as I can't reproduce the problem and there's been no further details/follow-up.

**Closed** 2022-08-31 23:52 UTC
